[project]
name = "pokedex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jose Javier Benito", email = "josejbenito57@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "requests>=2.34.2",
]

[project.scripts]
pokedex = "pokedex:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
